// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RM.Message.proto

package base.protobuf.message;

public final class RMMessage {
  private RMMessage() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IMMsgDataOrBuilder extends
          // @@protoc_insertion_point(interface_extends:RM.Message.IMMsgData)
          com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 from_user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0301
     * </pre>
     */
    boolean hasFromUserId();
    /**
     * <code>required uint32 from_user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0301
     * </pre>
     */
    int getFromUserId();

    /**
     * <code>required uint32 to_session_id = 2;</code>
     *
     * <pre>
     *消息接受方
     * </pre>
     */
    boolean hasToSessionId();
    /**
     * <code>required uint32 to_session_id = 2;</code>
     *
     * <pre>
     *消息接受方
     * </pre>
     */
    int getToSessionId();

    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    int getMsgId();

    /**
     * <code>required uint32 create_time = 4;</code>
     */
    boolean hasCreateTime();
    /**
     * <code>required uint32 create_time = 4;</code>
     */
    int getCreateTime();

    /**
     * <code>required .RM.BaseDefine.MsgType msg_type = 5;</code>
     */
    boolean hasMsgType();
    /**
     * <code>required .RM.BaseDefine.MsgType msg_type = 5;</code>
     */
    base.protobuf.basedefine.RMBaseDefine.MsgType getMsgType();

    /**
     * <code>required bytes msg_data = 6;</code>
     */
    boolean hasMsgData();
    /**
     * <code>required bytes msg_data = 6;</code>
     */
    com.google.protobuf.ByteString getMsgData();

    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    boolean hasAttachData();
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    com.google.protobuf.ByteString getAttachData();
  }
  /**
   * Protobuf type {@code RM.Message.IMMsgData}
   *
   * <pre>
   * 发送消息协议。
   * </pre>
   */
  public static final class IMMsgData extends
          com.google.protobuf.GeneratedMessageLite implements
          // @@protoc_insertion_point(message_implements:RM.Message.IMMsgData)
          IMMsgDataOrBuilder {
    // Use IMMsgData.newBuilder() to construct.
    private IMMsgData(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMMsgData(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMMsgData defaultInstance;
    public static IMMsgData getDefaultInstance() {
      return defaultInstance;
    }

    public IMMsgData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMMsgData(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
              com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
              com.google.protobuf.CodedOutputStream.newInstance(
                      unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              fromUserId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              toSessionId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgId_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              createTime_ = input.readUInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              base.protobuf.basedefine.RMBaseDefine.MsgType value = base.protobuf.basedefine.RMBaseDefine.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000010;
                msgType_ = value;
              }
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              msgData_ = input.readBytes();
              break;
            }
            case 162: {
              bitField0_ |= 0x00000040;
              attachData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
          // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMMsgData> PARSER =
            new com.google.protobuf.AbstractParser<IMMsgData>() {
              public IMMsgData parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new IMMsgData(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<IMMsgData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FROM_USER_ID_FIELD_NUMBER = 1;
    private int fromUserId_;
    /**
     * <code>required uint32 from_user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0301
     * </pre>
     */
    public boolean hasFromUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 from_user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0301
     * </pre>
     */
    public int getFromUserId() {
      return fromUserId_;
    }

    public static final int TO_SESSION_ID_FIELD_NUMBER = 2;
    private int toSessionId_;
    /**
     * <code>required uint32 to_session_id = 2;</code>
     *
     * <pre>
     *消息接受方
     * </pre>
     */
    public boolean hasToSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 to_session_id = 2;</code>
     *
     * <pre>
     *消息接受方
     * </pre>
     */
    public int getToSessionId() {
      return toSessionId_;
    }

    public static final int MSG_ID_FIELD_NUMBER = 3;
    private int msgId_;
    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    public static final int CREATE_TIME_FIELD_NUMBER = 4;
    private int createTime_;
    /**
     * <code>required uint32 create_time = 4;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 create_time = 4;</code>
     */
    public int getCreateTime() {
      return createTime_;
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 5;
    private base.protobuf.basedefine.RMBaseDefine.MsgType msgType_;
    /**
     * <code>required .RM.BaseDefine.MsgType msg_type = 5;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .RM.BaseDefine.MsgType msg_type = 5;</code>
     */
    public base.protobuf.basedefine.RMBaseDefine.MsgType getMsgType() {
      return msgType_;
    }

    public static final int MSG_DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString msgData_;
    /**
     * <code>required bytes msg_data = 6;</code>
     */
    public boolean hasMsgData() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bytes msg_data = 6;</code>
     */
    public com.google.protobuf.ByteString getMsgData() {
      return msgData_;
    }

    public static final int ATTACH_DATA_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString attachData_;
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public boolean hasAttachData() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes attach_data = 20;</code>
     */
    public com.google.protobuf.ByteString getAttachData() {
      return attachData_;
    }

    private void initFields() {
      fromUserId_ = 0;
      toSessionId_ = 0;
      msgId_ = 0;
      createTime_ = 0;
      msgType_ = base.protobuf.basedefine.RMBaseDefine.MsgType.MSG_TYPE_SINGLE_TEXT;
      msgData_ = com.google.protobuf.ByteString.EMPTY;
      attachData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFromUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, fromUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, toSessionId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, msgId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, createTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, msgType_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, msgData_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(20, attachData_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(1, fromUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(2, toSessionId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(3, msgId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(4, createTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(5, msgType_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(6, msgData_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(20, attachData_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static base.protobuf.message.RMMessage.IMMsgData parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static base.protobuf.message.RMMessage.IMMsgData parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static base.protobuf.message.RMMessage.IMMsgData parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static base.protobuf.message.RMMessage.IMMsgData parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static base.protobuf.message.RMMessage.IMMsgData parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static base.protobuf.message.RMMessage.IMMsgData parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static base.protobuf.message.RMMessage.IMMsgData parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static base.protobuf.message.RMMessage.IMMsgData parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static base.protobuf.message.RMMessage.IMMsgData parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static base.protobuf.message.RMMessage.IMMsgData parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(base.protobuf.message.RMMessage.IMMsgData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code RM.Message.IMMsgData}
     *
     * <pre>
     * 发送消息协议。
     * </pre>
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    base.protobuf.message.RMMessage.IMMsgData, Builder>
            implements
            // @@protoc_insertion_point(builder_implements:RM.Message.IMMsgData)
            base.protobuf.message.RMMessage.IMMsgDataOrBuilder {
      // Construct using base.protobuf.message.RMMessage.IMMsgData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        toSessionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        createTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        msgType_ = base.protobuf.basedefine.RMBaseDefine.MsgType.MSG_TYPE_SINGLE_TEXT;
        bitField0_ = (bitField0_ & ~0x00000010);
        msgData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        attachData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public base.protobuf.message.RMMessage.IMMsgData getDefaultInstanceForType() {
        return base.protobuf.message.RMMessage.IMMsgData.getDefaultInstance();
      }

      public base.protobuf.message.RMMessage.IMMsgData build() {
        base.protobuf.message.RMMessage.IMMsgData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public base.protobuf.message.RMMessage.IMMsgData buildPartial() {
        base.protobuf.message.RMMessage.IMMsgData result = new base.protobuf.message.RMMessage.IMMsgData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromUserId_ = fromUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toSessionId_ = toSessionId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgData_ = msgData_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.attachData_ = attachData_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(base.protobuf.message.RMMessage.IMMsgData other) {
        if (other == base.protobuf.message.RMMessage.IMMsgData.getDefaultInstance()) return this;
        if (other.hasFromUserId()) {
          setFromUserId(other.getFromUserId());
        }
        if (other.hasToSessionId()) {
          setToSessionId(other.getToSessionId());
        }
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasMsgData()) {
          setMsgData(other.getMsgData());
        }
        if (other.hasAttachData()) {
          setAttachData(other.getAttachData());
        }
        setUnknownFields(
                getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFromUserId()) {

          return false;
        }
        if (!hasToSessionId()) {

          return false;
        }
        if (!hasMsgId()) {

          return false;
        }
        if (!hasCreateTime()) {

          return false;
        }
        if (!hasMsgType()) {

          return false;
        }
        if (!hasMsgData()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        base.protobuf.message.RMMessage.IMMsgData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (base.protobuf.message.RMMessage.IMMsgData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int fromUserId_ ;
      /**
       * <code>required uint32 from_user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0301
       * </pre>
       */
      public boolean hasFromUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 from_user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0301
       * </pre>
       */
      public int getFromUserId() {
        return fromUserId_;
      }
      /**
       * <code>required uint32 from_user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0301
       * </pre>
       */
      public Builder setFromUserId(int value) {
        bitField0_ |= 0x00000001;
        fromUserId_ = value;

        return this;
      }
      /**
       * <code>required uint32 from_user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0301
       * </pre>
       */
      public Builder clearFromUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromUserId_ = 0;

        return this;
      }

      private int toSessionId_ ;
      /**
       * <code>required uint32 to_session_id = 2;</code>
       *
       * <pre>
       *消息接受方
       * </pre>
       */
      public boolean hasToSessionId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 to_session_id = 2;</code>
       *
       * <pre>
       *消息接受方
       * </pre>
       */
      public int getToSessionId() {
        return toSessionId_;
      }
      /**
       * <code>required uint32 to_session_id = 2;</code>
       *
       * <pre>
       *消息接受方
       * </pre>
       */
      public Builder setToSessionId(int value) {
        bitField0_ |= 0x00000002;
        toSessionId_ = value;

        return this;
      }
      /**
       * <code>required uint32 to_session_id = 2;</code>
       *
       * <pre>
       *消息接受方
       * </pre>
       */
      public Builder clearToSessionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toSessionId_ = 0;

        return this;
      }

      private int msgId_ ;
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public Builder setMsgId(int value) {
        bitField0_ |= 0x00000004;
        msgId_ = value;

        return this;
      }
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgId_ = 0;

        return this;
      }

      private int createTime_ ;
      /**
       * <code>required uint32 create_time = 4;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 create_time = 4;</code>
       */
      public int getCreateTime() {
        return createTime_;
      }
      /**
       * <code>required uint32 create_time = 4;</code>
       */
      public Builder setCreateTime(int value) {
        bitField0_ |= 0x00000008;
        createTime_ = value;

        return this;
      }
      /**
       * <code>required uint32 create_time = 4;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createTime_ = 0;

        return this;
      }

      private base.protobuf.basedefine.RMBaseDefine.MsgType msgType_ = base.protobuf.basedefine.RMBaseDefine.MsgType.MSG_TYPE_SINGLE_TEXT;
      /**
       * <code>required .RM.BaseDefine.MsgType msg_type = 5;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .RM.BaseDefine.MsgType msg_type = 5;</code>
       */
      public base.protobuf.basedefine.RMBaseDefine.MsgType getMsgType() {
        return msgType_;
      }
      /**
       * <code>required .RM.BaseDefine.MsgType msg_type = 5;</code>
       */
      public Builder setMsgType(base.protobuf.basedefine.RMBaseDefine.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        msgType_ = value;

        return this;
      }
      /**
       * <code>required .RM.BaseDefine.MsgType msg_type = 5;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgType_ = base.protobuf.basedefine.RMBaseDefine.MsgType.MSG_TYPE_SINGLE_TEXT;

        return this;
      }

      private com.google.protobuf.ByteString msgData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes msg_data = 6;</code>
       */
      public boolean hasMsgData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bytes msg_data = 6;</code>
       */
      public com.google.protobuf.ByteString getMsgData() {
        return msgData_;
      }
      /**
       * <code>required bytes msg_data = 6;</code>
       */
      public Builder setMsgData(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        msgData_ = value;

        return this;
      }
      /**
       * <code>required bytes msg_data = 6;</code>
       */
      public Builder clearMsgData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgData_ = getDefaultInstance().getMsgData();

        return this;
      }

      private com.google.protobuf.ByteString attachData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public boolean hasAttachData() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public com.google.protobuf.ByteString getAttachData() {
        return attachData_;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder setAttachData(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        attachData_ = value;

        return this;
      }
      /**
       * <code>optional bytes attach_data = 20;</code>
       */
      public Builder clearAttachData() {
        bitField0_ = (bitField0_ & ~0x00000040);
        attachData_ = getDefaultInstance().getAttachData();

        return this;
      }

      // @@protoc_insertion_point(builder_scope:RM.Message.IMMsgData)
    }

    static {
      defaultInstance = new IMMsgData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RM.Message.IMMsgData)
  }

  public interface IMMsgDataAckOrBuilder extends
          // @@protoc_insertion_point(interface_extends:RM.Message.IMMsgDataAck)
          com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0302
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0302
     * </pre>
     */
    int getUserId();

    /**
     * <code>required uint32 session_id = 2;</code>
     */
    boolean hasSessionId();
    /**
     * <code>required uint32 session_id = 2;</code>
     */
    int getSessionId();

    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    int getMsgId();

    /**
     * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
     */
    boolean hasSessionType();
    /**
     * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
     */
    base.protobuf.basedefine.RMBaseDefine.SessionType getSessionType();
  }
  /**
   * Protobuf type {@code RM.Message.IMMsgDataAck}
   *
   * <pre>
   * 消息收到回复。
   * </pre>
   */
  public static final class IMMsgDataAck extends
          com.google.protobuf.GeneratedMessageLite implements
          // @@protoc_insertion_point(message_implements:RM.Message.IMMsgDataAck)
          IMMsgDataAckOrBuilder {
    // Use IMMsgDataAck.newBuilder() to construct.
    private IMMsgDataAck(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMMsgDataAck(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMMsgDataAck defaultInstance;
    public static IMMsgDataAck getDefaultInstance() {
      return defaultInstance;
    }

    public IMMsgDataAck getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMMsgDataAck(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
              com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
              com.google.protobuf.CodedOutputStream.newInstance(
                      unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sessionId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgId_ = input.readUInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              base.protobuf.basedefine.RMBaseDefine.SessionType value = base.protobuf.basedefine.RMBaseDefine.SessionType.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000008;
                sessionType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
          // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMMsgDataAck> PARSER =
            new com.google.protobuf.AbstractParser<IMMsgDataAck>() {
              public IMMsgDataAck parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new IMMsgDataAck(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<IMMsgDataAck> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0302
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0302
     * </pre>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int SESSION_ID_FIELD_NUMBER = 2;
    private int sessionId_;
    /**
     * <code>required uint32 session_id = 2;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 session_id = 2;</code>
     */
    public int getSessionId() {
      return sessionId_;
    }

    public static final int MSG_ID_FIELD_NUMBER = 3;
    private int msgId_;
    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    public static final int SESSION_TYPE_FIELD_NUMBER = 4;
    private base.protobuf.basedefine.RMBaseDefine.SessionType sessionType_;
    /**
     * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
     */
    public boolean hasSessionType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
     */
    public base.protobuf.basedefine.RMBaseDefine.SessionType getSessionType() {
      return sessionType_;
    }

    private void initFields() {
      userId_ = 0;
      sessionId_ = 0;
      msgId_ = 0;
      sessionType_ = base.protobuf.basedefine.RMBaseDefine.SessionType.SESSION_TYPE_SINGLE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, sessionId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, msgId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, sessionType_.getNumber());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(2, sessionId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(3, msgId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(4, sessionType_.getNumber());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static base.protobuf.message.RMMessage.IMMsgDataAck parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataAck parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataAck parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataAck parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataAck parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataAck parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataAck parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataAck parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataAck parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataAck parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(base.protobuf.message.RMMessage.IMMsgDataAck prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code RM.Message.IMMsgDataAck}
     *
     * <pre>
     * 消息收到回复。
     * </pre>
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    base.protobuf.message.RMMessage.IMMsgDataAck, Builder>
            implements
            // @@protoc_insertion_point(builder_implements:RM.Message.IMMsgDataAck)
            base.protobuf.message.RMMessage.IMMsgDataAckOrBuilder {
      // Construct using base.protobuf.message.RMMessage.IMMsgDataAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionType_ = base.protobuf.basedefine.RMBaseDefine.SessionType.SESSION_TYPE_SINGLE;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public base.protobuf.message.RMMessage.IMMsgDataAck getDefaultInstanceForType() {
        return base.protobuf.message.RMMessage.IMMsgDataAck.getDefaultInstance();
      }

      public base.protobuf.message.RMMessage.IMMsgDataAck build() {
        base.protobuf.message.RMMessage.IMMsgDataAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public base.protobuf.message.RMMessage.IMMsgDataAck buildPartial() {
        base.protobuf.message.RMMessage.IMMsgDataAck result = new base.protobuf.message.RMMessage.IMMsgDataAck(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sessionType_ = sessionType_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(base.protobuf.message.RMMessage.IMMsgDataAck other) {
        if (other == base.protobuf.message.RMMessage.IMMsgDataAck.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasSessionType()) {
          setSessionType(other.getSessionType());
        }
        setUnknownFields(
                getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {

          return false;
        }
        if (!hasSessionId()) {

          return false;
        }
        if (!hasMsgId()) {

          return false;
        }
        if (!hasSessionType()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        base.protobuf.message.RMMessage.IMMsgDataAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (base.protobuf.message.RMMessage.IMMsgDataAck) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0302
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0302
       * </pre>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0302
       * </pre>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;

        return this;
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0302
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;

        return this;
      }

      private int sessionId_ ;
      /**
       * <code>required uint32 session_id = 2;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 session_id = 2;</code>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <code>required uint32 session_id = 2;</code>
       */
      public Builder setSessionId(int value) {
        bitField0_ |= 0x00000002;
        sessionId_ = value;

        return this;
      }
      /**
       * <code>required uint32 session_id = 2;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = 0;

        return this;
      }

      private int msgId_ ;
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public Builder setMsgId(int value) {
        bitField0_ |= 0x00000004;
        msgId_ = value;

        return this;
      }
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgId_ = 0;

        return this;
      }

      private base.protobuf.basedefine.RMBaseDefine.SessionType sessionType_ = base.protobuf.basedefine.RMBaseDefine.SessionType.SESSION_TYPE_SINGLE;
      /**
       * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
       */
      public boolean hasSessionType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
       */
      public base.protobuf.basedefine.RMBaseDefine.SessionType getSessionType() {
        return sessionType_;
      }
      /**
       * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
       */
      public Builder setSessionType(base.protobuf.basedefine.RMBaseDefine.SessionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        sessionType_ = value;

        return this;
      }
      /**
       * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
       */
      public Builder clearSessionType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sessionType_ = base.protobuf.basedefine.RMBaseDefine.SessionType.SESSION_TYPE_SINGLE;

        return this;
      }

      // @@protoc_insertion_point(builder_scope:RM.Message.IMMsgDataAck)
    }

    static {
      defaultInstance = new IMMsgDataAck(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RM.Message.IMMsgDataAck)
  }

  public interface IMMsgDataReadAckOrBuilder extends
          // @@protoc_insertion_point(interface_extends:RM.Message.IMMsgDataReadAck)
          com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0303
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0303
     * </pre>
     */
    int getUserId();

    /**
     * <code>required uint32 session_id = 2;</code>
     */
    boolean hasSessionId();
    /**
     * <code>required uint32 session_id = 2;</code>
     */
    int getSessionId();

    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    int getMsgId();

    /**
     * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
     */
    boolean hasSessionType();
    /**
     * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
     */
    base.protobuf.basedefine.RMBaseDefine.SessionType getSessionType();
  }
  /**
   * Protobuf type {@code RM.Message.IMMsgDataReadAck}
   *
   * <pre>
   * 消息已读回复。
   * </pre>
   */
  public static final class IMMsgDataReadAck extends
          com.google.protobuf.GeneratedMessageLite implements
          // @@protoc_insertion_point(message_implements:RM.Message.IMMsgDataReadAck)
          IMMsgDataReadAckOrBuilder {
    // Use IMMsgDataReadAck.newBuilder() to construct.
    private IMMsgDataReadAck(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMMsgDataReadAck(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMMsgDataReadAck defaultInstance;
    public static IMMsgDataReadAck getDefaultInstance() {
      return defaultInstance;
    }

    public IMMsgDataReadAck getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMMsgDataReadAck(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
              com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
              com.google.protobuf.CodedOutputStream.newInstance(
                      unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sessionId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgId_ = input.readUInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              base.protobuf.basedefine.RMBaseDefine.SessionType value = base.protobuf.basedefine.RMBaseDefine.SessionType.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000008;
                sessionType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
          // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMMsgDataReadAck> PARSER =
            new com.google.protobuf.AbstractParser<IMMsgDataReadAck>() {
              public IMMsgDataReadAck parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new IMMsgDataReadAck(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<IMMsgDataReadAck> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0303
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 user_id = 1;</code>
     *
     * <pre>
     *cmd id:		0x0303
     * </pre>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int SESSION_ID_FIELD_NUMBER = 2;
    private int sessionId_;
    /**
     * <code>required uint32 session_id = 2;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 session_id = 2;</code>
     */
    public int getSessionId() {
      return sessionId_;
    }

    public static final int MSG_ID_FIELD_NUMBER = 3;
    private int msgId_;
    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 msg_id = 3;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    public static final int SESSION_TYPE_FIELD_NUMBER = 4;
    private base.protobuf.basedefine.RMBaseDefine.SessionType sessionType_;
    /**
     * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
     */
    public boolean hasSessionType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
     */
    public base.protobuf.basedefine.RMBaseDefine.SessionType getSessionType() {
      return sessionType_;
    }

    private void initFields() {
      userId_ = 0;
      sessionId_ = 0;
      msgId_ = 0;
      sessionType_ = base.protobuf.basedefine.RMBaseDefine.SessionType.SESSION_TYPE_SINGLE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, sessionId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, msgId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, sessionType_.getNumber());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(2, sessionId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(3, msgId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(4, sessionType_.getNumber());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static base.protobuf.message.RMMessage.IMMsgDataReadAck parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataReadAck parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataReadAck parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataReadAck parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataReadAck parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataReadAck parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataReadAck parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataReadAck parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataReadAck parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static base.protobuf.message.RMMessage.IMMsgDataReadAck parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(base.protobuf.message.RMMessage.IMMsgDataReadAck prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code RM.Message.IMMsgDataReadAck}
     *
     * <pre>
     * 消息已读回复。
     * </pre>
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    base.protobuf.message.RMMessage.IMMsgDataReadAck, Builder>
            implements
            // @@protoc_insertion_point(builder_implements:RM.Message.IMMsgDataReadAck)
            base.protobuf.message.RMMessage.IMMsgDataReadAckOrBuilder {
      // Construct using base.protobuf.message.RMMessage.IMMsgDataReadAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sessionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionType_ = base.protobuf.basedefine.RMBaseDefine.SessionType.SESSION_TYPE_SINGLE;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public base.protobuf.message.RMMessage.IMMsgDataReadAck getDefaultInstanceForType() {
        return base.protobuf.message.RMMessage.IMMsgDataReadAck.getDefaultInstance();
      }

      public base.protobuf.message.RMMessage.IMMsgDataReadAck build() {
        base.protobuf.message.RMMessage.IMMsgDataReadAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public base.protobuf.message.RMMessage.IMMsgDataReadAck buildPartial() {
        base.protobuf.message.RMMessage.IMMsgDataReadAck result = new base.protobuf.message.RMMessage.IMMsgDataReadAck(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sessionType_ = sessionType_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(base.protobuf.message.RMMessage.IMMsgDataReadAck other) {
        if (other == base.protobuf.message.RMMessage.IMMsgDataReadAck.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasSessionType()) {
          setSessionType(other.getSessionType());
        }
        setUnknownFields(
                getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {

          return false;
        }
        if (!hasSessionId()) {

          return false;
        }
        if (!hasMsgId()) {

          return false;
        }
        if (!hasSessionType()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        base.protobuf.message.RMMessage.IMMsgDataReadAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (base.protobuf.message.RMMessage.IMMsgDataReadAck) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0303
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0303
       * </pre>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0303
       * </pre>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;

        return this;
      }
      /**
       * <code>required uint32 user_id = 1;</code>
       *
       * <pre>
       *cmd id:		0x0303
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;

        return this;
      }

      private int sessionId_ ;
      /**
       * <code>required uint32 session_id = 2;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 session_id = 2;</code>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <code>required uint32 session_id = 2;</code>
       */
      public Builder setSessionId(int value) {
        bitField0_ |= 0x00000002;
        sessionId_ = value;

        return this;
      }
      /**
       * <code>required uint32 session_id = 2;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = 0;

        return this;
      }

      private int msgId_ ;
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public Builder setMsgId(int value) {
        bitField0_ |= 0x00000004;
        msgId_ = value;

        return this;
      }
      /**
       * <code>required uint32 msg_id = 3;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgId_ = 0;

        return this;
      }

      private base.protobuf.basedefine.RMBaseDefine.SessionType sessionType_ = base.protobuf.basedefine.RMBaseDefine.SessionType.SESSION_TYPE_SINGLE;
      /**
       * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
       */
      public boolean hasSessionType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
       */
      public base.protobuf.basedefine.RMBaseDefine.SessionType getSessionType() {
        return sessionType_;
      }
      /**
       * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
       */
      public Builder setSessionType(base.protobuf.basedefine.RMBaseDefine.SessionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        sessionType_ = value;

        return this;
      }
      /**
       * <code>required .RM.BaseDefine.SessionType session_type = 4;</code>
       */
      public Builder clearSessionType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sessionType_ = base.protobuf.basedefine.RMBaseDefine.SessionType.SESSION_TYPE_SINGLE;

        return this;
      }

      // @@protoc_insertion_point(builder_scope:RM.Message.IMMsgDataReadAck)
    }

    static {
      defaultInstance = new IMMsgDataReadAck(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RM.Message.IMMsgDataReadAck)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
